### ISSUE TITLE
Adding port pages

### ISSUE THREAD

**Issue by derickfan** [DataMascara/cisc3140-su19-project#19]
-Let's you see all the posts from a port

**Comment by LoadingUser3** [comment]
I am able to select each port from the Trending ports menu and from the View Port Index page while logged in. 

I cannot fully see an individual post though, even if I click on it.

**p/ Main:**

![image](https://user-images.githubusercontent.com/47548948/62910517-cca56180-bd4e-11e9-800b-945a3f0192ea.png)

**p/ Textbooks:**

![image](https://user-images.githubusercontent.com/47548948/62910527-d3cc6f80-bd4e-11e9-86b2-8058b86aa536.png)

**p/ Events:**

![image](https://user-images.githubusercontent.com/47548948/62910532-da5ae700-bd4e-11e9-8614-8fe81dfdae8d.png)

**p/ CampusFood:**

![image](https://user-images.githubusercontent.com/47548948/62910546-e646a900-bd4e-11e9-8e58-48c36cdc8af1.png)


**p/ CIS:**

![image](https://user-images.githubusercontent.com/47548948/62910548-ec3c8a00-bd4e-11e9-823a-fa044bbab79c.png)


**p/ BrokelynCollege:**

![image](https://user-images.githubusercontent.com/47548948/62910558-f2326b00-bd4e-11e9-94fa-cbad2f3ac1b5.png)

**Comment by Maker-Mark** [comment]
> I am able to select each port from the Trending ports menu and from the View Port Index page while logged in.
> 
> I cannot fully see an individual post though, even if I click on it.
> 
> **p/ Main:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910517-cca56180-bd4e-11e9-800b-945a3f0192ea.png)
> 
> **p/ Textbooks:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910527-d3cc6f80-bd4e-11e9-86b2-8058b86aa536.png)
> 
> **p/ Events:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910532-da5ae700-bd4e-11e9-8614-8fe81dfdae8d.png)
> 
> **p/ CampusFood:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910546-e646a900-bd4e-11e9-8e58-48c36cdc8af1.png)
> 
> **p/ CIS:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910548-ec3c8a00-bd4e-11e9-823a-fa044bbab79c.png)
> 
> **p/ BrokelynCollege:**
> 
> ![image](https://user-images.githubusercontent.com/47548948/62910558-f2326b00-bd4e-11e9-94fa-cbad2f3ac1b5.png)

You should now be able to click on a post and view it, comment's are not displaying, persisting or rendering yet.

**Comment by Maker-Mark** [comment]
Please reopen if this issue happens again. Closed
