### ISSUE TITLE
Viewing posts from users's subscribed ports

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#24]
API:
- Work though logic to view list of subscriptions of a given user
- Send list of subscriptions back in easy to iterate form (ie list of dict)
Calling_Api:
- Given current user, use API to get list of subscribed posts.
- Get the ports and display them in a feed

**Comment by mary060196** [comment]
Since the End Point has been successfully connected to each user's homepage, this issue is closed.
Thanks!
