### ISSUE TITLE
Bad Request Key Error when Hitting Enter While Search Field is Empty

### ISSUE THREAD

**Issue by LoadingUser3** [DataMascara/cisc3140-su19-project#26]
Hitting enter while Search field is empty in the /login/ page results in a Key Error.

**Steps to replicate:**
1.	Go to Url: 127.0.0.1:8080/login/
2.	Click on the Search field
3.	Hit Enter.

**Result:** wekzeug.exceptions.BadRequestKeyError

Screenshots:
![image](https://user-images.githubusercontent.com/47548948/62837122-bf4a8300-bc39-11e9-8d76-d49f887102c2.png)

![image](https://user-images.githubusercontent.com/47548948/62837123-c5406400-bc39-11e9-8a1e-fa60600259f5.png)

**Extra Notes:**

•	Error does not show when in the Url is http://127.0.0.1:8080/signup. Instead, it gives a Method Not allowed error.

**Comment by mary060196** [comment]
Hey, @LoadingUser3 and @Maker-Mark !
I want to change one line of code in the `base.html` so that empty searches would not be submitted. I already have the code, and I just need to paste it into one of the lines.
Will this cause issues with the deployment of the application?

**Comment by mary060196** [comment]
Hello @Maker-Mark ,
The `base.html` template was changed such that an empty search (when it will be implemented) will never be submitted when it is empty.
Please check this out by clicking ENTER when there is a focus on the search box (it was added no to much time ago, so please retrieve the lastest template.
Thank you very much!

**Comment by LoadingUser3** [comment]
No errors when enter is hit while search field is empty!

Fantastic job.

**Comment by mary060196** [comment]
Woohoo! Thanks, and good job!
