### ISSUE TITLE
Add API and calling API for up votes/down votes

### ISSUE THREAD

**Issue by derickfan** [DataMascara/cisc3140-su19-project#30]

**Comment by kennish1997** [comment]
When upvoting/downvoting a comment, it applies to the first comment
<img width="951" alt="2019-08-13 (3)" src="https://user-images.githubusercontent.com/49169064/62983644-22851280-bdfe-11e9-95aa-59c33c8c784e.png">

**Comment by Maker-Mark** [comment]
> When upvoting/downvoting a comment, it applies to the first comment
> <img alt="2019-08-13 (3)" width="951" src="https://user-images.githubusercontent.com/49169064/62983644-22851280-bdfe-11e9-95aa-59c33c8c784e.png">

Resolved! (still a bit finicky, please open a new issue if you find the new bugs)
