### ISSUE TITLE
Backend: Generate and send User Page Data

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#31]
- Populate the `userInfo.html` template with users' information.

**Comment by xiaojun-wu** [comment]
Are you still working it? I am sorry I didn't see it and I did some of that.

**Comment by Maker-Mark** [comment]
> Are you still working it? I am sorry I didn't see it and I did some of that.
I got the bare bones done a while back, but I saw you did a lot for this and the other dashboard related things, thank you.
Closing this issue and opening a new one about the "myposts" tab.
