### ISSUE TITLE
Frontend:  New post bugs: Add Dropdown to select a port, etc

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#35]
- Currently, making a new post allows a user to type in any "community"(really port, right and submit it)
- Could you implement a drop down menu (or something that will list the ports that already exist)
- Ie we can send you a list of the current ports, then you can add that to the drop down menu. This way we ensure the post get's added and the user knows that they selected a port that exists. If the post fails, ie post with title already exits, we will return an error
- Other note: Please remove Username Field, we now store it locally, and send it over. 
- Is it intentional that it says "community" instead of port?

-- Thank you :)

**Comment by mary060196** [comment]
@Maker-Mark , are you able to see if this particular issue (with the dropdown menu) is fixed after the code was changed? Thank you for this!

**Comment by Maker-Mark** [comment]
> @Maker-Mark , are you able to see if this particular issue (with the dropdown menu) is fixed after the code was changed? Thank you for this!

Looking into this now, will touch back soon..

**Comment by Maker-Mark** [comment]
@mary060196 
This is now working as we spoke about, very nice!
