### ISSUE TITLE
Registered to Website, but Now It Says `Internal Server Error 500`

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#42]
I registered, and then pressed the `View Port Index` button. Then, this message appeared. It keeps appearing on any other page that I go to. What to do?

**Comment by Maker-Mark** [comment]
> I registered, and then pressed the `View Port Index` button. Then, this message appeared. It keeps appearing on any other page that I go to. What to do?

I was unable to reproduce this bug. I just made a new account, went around the web site, logged out, logged in again and was able to see the port index fine. 
- Please reproduce this bug again and reopen the issue

**Comment by mary060196** [comment]
![image](https://user-images.githubusercontent.com/52957236/62975791-370ae000-bde9-11e9-9020-feccc1ec94d9.png)
This is what I see when I enter the website.

**Comment by derickfan** [comment]
It seems like some session things aren't being set after signing up I'll fix that right away. You can just logout by going to https://bc-app-class.herokuapp.com/logout/ and then log back in

**Comment by mary060196** [comment]
Yea! Fixed! Thank you so much!!! I close the issue.
