### ISSUE TITLE
Profile issues: Clicking on subscriptions from dashboard does not take you to the port

### ISSUE THREAD

**Issue by AlekseyTitov99** [DataMascara/cisc3140-su19-project#45]
~~Dashboard has the same page as user profile~~
- Subscriptions don't work at all

**Comment by mary060196** [comment]
The Dashboard page is already being attended by the Back End team. The subscriptions and 'my posts' pages are already on, and the others are on the way.
Thank you very much!

**Comment by Maker-Mark** [comment]
> * Dashboard has the same page as user profile

Now it's updated. 


> * Subscriptions don't work at all

They now show up on the dashboard, we are working on linking them

**Comment by Maker-Mark** [comment]
Fixed, clicking on your subscribed ports works now too
