### ISSUE TITLE
Pulling from master branch unsuccessful 

### ISSUE THREAD

**Issue by darienmiller88** [DataMascara/cisc3140-su19-project#46]
When I attempted to clone from the master branch into pycharm, accessing the python files resulted in several errors, such as function calls not being recognized.

**Comment by abrahym-sharfeldden** [comment]
What errors are you getting? Could you paste it in or show images?

**Comment by Maker-Mark** [comment]
Closing this issue here as it does not relate to the functionality of the app.
Feel free to PM me, I'd love to help if i can
