### ISSUE TITLE
Logo Change?

### ISSUE THREAD

**Issue by kennish1997** [DataMascara/cisc3140-su19-project#47]

**Comment by mary060196** [comment]
Logo & title for the website will be changed by midnight today.

**Comment by mary060196** [comment]
Hey, @kennish1997 !
I just changed the Logo and the Icon for the website. Once the website re-deploys, it will show the changes. Make sure to refresh the page when the site is redeployed and the changes are not seen.
Thank you for your patience!

**Comment by mary060196** [comment]
Sorry! I initially uploaded an icon file with the wrong name. Now it is fixed. Please try to re-deploy again.
Thank you very, very much for your help!
