### ISSUE TITLE
Image URL when creating a post doesn’t work

### ISSUE THREAD

**Issue by kennish1997** [DataMascara/cisc3140-su19-project#49]
-Image URL when creating a post doesn’t work, only display the cat
-When adding links while creating a post, nothing shows up
<img width="433" alt="Capture" src="https://user-images.githubusercontent.com/49169064/62990593-8cabb080-be1a-11e9-9faf-99b5b27ab294.PNG">

**Comment by Maker-Mark** [comment]
> -Image URL when creating a post doesn’t work, only display the cat
> -When adding links while creating a post, nothing shows up
> <img alt="Capture" width="433" src="https://user-images.githubusercontent.com/49169064/62990593-8cabb080-be1a-11e9-9faf-99b5b27ab294.PNG">

Issue resolved!
