### ISSUE TITLE
Trending Ports on past page

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#53]
- Cache trending ports, add and pop them in sessions

**Comment by mary060196** [comment]
@Maker-Mark , it is good that you raise this issue. Clicking on a Trending Ports subscription button produces a message like in the following pic:
![image](https://user-images.githubusercontent.com/52957236/62993077-f9777880-be23-11e9-8e4c-5f47a5903f79.png)
I am so much thankful to you for your attention!

**Comment by Maker-Mark** [comment]
> @Maker-Mark , it is good that you raise this issue. Clicking on a Trending Ports subscription button produces a message like in the following pic:
> ![image](https://user-images.githubusercontent.com/52957236/62993077-f9777880-be23-11e9-8e4c-5f47a5903f79.png)
> I am so much thankful to you for your attention!

Ahah yes yes, Derick got to fixing it very fast, I think it's fine now.
