### ISSUE TITLE
Add "authorImg" attribute to posts

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#54]
- We need a way to get a post's author's image url
- Please add a field called "authorUrl" to every post, and add the additional needed parameter for the related methods (ie adding post now will take the user's avararurl and store it as the post's authorImg

- Thanks

**Comment by chalshaff12** [comment]
I added the author's avatar URL to the posts view so the authorImg column should be showing up now with the post data
