### ISSUE TITLE
500 Internal Server Error after Changing Bio + Avatar

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#55]
![image](https://user-images.githubusercontent.com/52957236/62993478-6d665080-be25-11e9-8a66-b25fc9270905.png)
@Maker-Mark , why is this?
Please, excuse me for this pressure. I was just excited and wanted to see how it works, so I changed the bio and image URL.

**Comment by Maker-Mark** [comment]
It's fixed

**Comment by mary060196** [comment]
Wonderful work!!!
