### ISSUE TITLE
 Visuals: Homepage and commenting button

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#57]
When you're not logged in, currently the home page is empty. 
Is that the intended splash page or will there be a image or feed that will demo the site for potential users?

**Comment by Maker-Mark** [comment]
- Also, there is a profile img that is called "bully.png" in the img folder. We were using it as a debug, and it looked really nice. 
- A suggestion came up to pass it on to you all to be the default img if a user doesn't choose one.
- it's already a transparent png of the bc bulldog :)

**Comment by mary060196** [comment]
Hello, @Maker-Mark .
First, I'd like to thank you for your messages and for the great effort that you contributed to the website! It is, indeed, a great idea if it could somehow be used by the CS dept.
About the homepage for those who are logged out: the Product team intended to see a page of posts from different ports on the page. There is no ability to vote for them, but people can see the details of posts if they click on the title of a post.
The posts should be initially sorted by date, such that the most recent posts are at the top of the page. The `posts.html` template checks if the user argument was passed to distinguish between a user who views the page and a non-user. In other words, the `posts.html` page should be used for non-users as well.
If there are any questions about this, please do not hesitate to ask! 
Thank you so much!

**Comment by Maker-Mark** [comment]
@mary060196 
Great, we now have it rendering it, however if a user tries to click on a post, and is not logged in, should they be allowed to view it? I dont think so, right?
- If so, can you add a slide-in msg that tells you to sign up if no user is passed into the posts? Ie "you need to login or be a member to view this" and so on?

**Comment by Maker-Mark** [comment]
Additionally, @mary060196  the comment box only submits when someone hits enter, can you add a input submit and have it go to the link we have currently set? People should be able to hit new lines in comments, right?

**Comment by mary060196** [comment]
You're right; I understand your concern. However, the Product team still wishes that this feature holds. If the user argument is not given to the template, it hides the commenting options, the "save posts" button, and the "++" and "--" buttons, so that a non-user can only see the post, but not interact with it. What do you think should be done, @Maker-Mark ?

**Comment by mary060196** [comment]
I'll add the submission buttons, and notify you once it is done. Thank you, @Maker-Mark !

**Comment by mary060196** [comment]
@Maker-Mark !
Comment to Comment buttons were added! I even wrote one comment to @derickfan 's post and tried the button out! Try it too!
Thanks!

**Comment by Maker-Mark** [comment]
Fixed, Thank you!
