### ISSUE TITLE
Changing User Profile img does not stick until you logout and log back in.

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#59]
- Maybe try and re assign the session['user'] via a get user call to the api, this way the user does not need to log out for the local user info to get updated

**Comment by andrewalexgit** [comment]
This is actually an issue with all account update features --- I will add a session refresh method to the template render application which can be easily called from any update method

**Comment by andrewalexgit** [comment]
Seems like we already have a refresh for the session added

`session["user"]["avatarUrl"] = form["avatarURL"]`

Could this be an issue with browser cache?

**Comment by Maker-Mark** [comment]
> Seems like we already have a refresh for the session added
> 
> `session["user"]["avatarUrl"] = form["avatarURL"]`
> 
> Could this be an issue with browser cache?

Yes, it is. We need to pop the current user img from the cookie and re-assign the new one.
This means we need to call the db to get the updated user, and just fish out the new URL

**Comment by mary060196** [comment]
Issue resolved and, thus, closed! Great job! :)
