### ISSUE TITLE
postDetails page is doing everything twice

### ISSUE THREAD

**Issue by derickfan** [DataMascara/cisc3140-su19-project#60]
![Screen Shot 2019-08-14 at 1 34 35 PM](https://user-images.githubusercontent.com/22162773/63042574-514fc700-be98-11e9-82e8-901f4bd34c0b.png)

Every time we load the page it will run it twice. So if we commented on a post it would post two comments. What is this script for?
![Screen Shot 2019-08-14 at 1 35 56 PM](https://user-images.githubusercontent.com/22162773/63042711-9a078000-be98-11e9-87b8-83305cc50e75.png)

**Comment by mary060196** [comment]
Hey, @derickfan and @Maker-Mark !
This code has been added so that users do not have to refresh a page twice. The question is, why is the comment submitted twice? If I remove this JS code, will the users need to refresh the page manually to see the comment they wrote?
Thanks for the reply!

**Comment by Maker-Mark** [comment]
> Hey, @derickfan and @Maker-Mark !
> This code has been added so that users do not have to refresh a page twice. The question is, why is the comment submitted twice? If I remove this JS code, will the users need to refresh the page manually to see the comment they wrote?
> Thanks for the reply!

We fixed the duplicate posting and added a refresh on commenting. All should be good. Closing this for now
