### ISSUE TITLE
DashBoard: "MyPosts" display squished.

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#61]
The "my posts" tab is looking a bit rough.
The posts are being squished and you cannot see them or click on them.
See img below
![image](https://user-images.githubusercontent.com/40143016/63043477-51e95d00-be9a-11e9-9bfa-f2e015ca4908.png)

**Comment by mary060196** [comment]
@Maker-Mark ,
could you try to see how it looks now?

**Comment by Maker-Mark** [comment]
@mary060196 Still happening :(
![image](https://user-images.githubusercontent.com/40143016/63048133-e1dfd480-bea3-11e9-8847-06426e7fd454.png)

**Comment by mary060196** [comment]
@Maker-Mark , we'll try to see. Does the same happen in the comments & saved posts tabs?

**Comment by mary060196** [comment]
@Maker-Mark , try to check it now; I added a "min-height" CSS code.
Also, what is your screen's height in pixels?

**Comment by Maker-Mark** [comment]
It looks okay only if you have just a few post.
![image](https://user-images.githubusercontent.com/40143016/63055834-be715580-beb4-11e9-909a-1019641f60b1.png)

**Comment by mary060196** [comment]
Thank you for notifying! I'll check this later today.

**Comment by mary060196** [comment]
@Maker-Mark , I was happy to see that posts are properly displayed now!
