### ISSUE TITLE
Limit profile IMG url length

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#62]
Some profile images are far too long and create issues for the cookie processing.
For now, please limit the length of a IMG url to 300 characters on any place a img can be submitted

**Comment by mary060196** [comment]
@Maker-Mark !
Will be done in an hour across the website.

**Comment by Maker-Mark** [comment]
> @Maker-Mark !
> Will be done in an hour across the website.

Thank you!
