### ISSUE TITLE
Sort "hot"

### ISSUE THREAD

**Issue by derickfan** [DataMascara/cisc3140-su19-project#63]
Posts should now all be sorted by new by default and you can also sort by hot. However when you sort by hot and the page refreshes the sort option goes back to new. So you cannot sort by new again once you sort by hot. You can refresh the page however to reset it to sorting by new.
![Screen Shot 2019-08-14 at 4 05 34 PM](https://user-images.githubusercontent.com/22162773/63052459-608d3f80-bead-11e9-91f5-015993ca15ef.png)

**Comment by mary060196** [comment]
Yes! That's indeed an issue.
What could be done is adding a Jinja `if` that checks if an argument called `hot` was passed to the template, and then make the selected option according to the passed argument. As you noticed, the `new` option is selected by default, which is the problem. I'll add this Jinja `if` and will notify you!
Thank you very much for pointing this out!

**Comment by mary060196** [comment]
Hi, @derickfan !
I just added the Jinja code for "new" and "hot. If `new` is passed to the template (whatever its type is and its value is), the sort dropdown will write `Sort by: New`. If `hot` is passed, it'll write `Sort by: Hot`. It is just left to send the arguments in the Back End python code.
Hope it solved the problem!

**Comment by derickfan** [comment]
Hey I'm looking at the template and I'm confused as to what exactly I'm supposed to pass in as a arguement. Also wouldn't it be better if we had it the old way but have the default value be just "Sort" like we have it when the user creates a post?
![Screen Shot 2019-08-16 at 9 07 11 PM](https://user-images.githubusercontent.com/22162773/63204831-f66dc980-c069-11e9-89a3-41f5fa5dd0c5.png)

**Comment by mary060196** [comment]
@derickfan , thank you very much for your question. The `hot` and `new` parameters about which I spoke earlier can be of any type, and can have any content. The 'posts.html' template checks which one of them has been passed. If, for example, you pass `new = True` inside the `render_template` function, then the default value of the sort menu will be `Sort by: New`. The list of posts that you are passing as an argument must then be sorted such that the most recent post comes first. When the user submits this form with the selected option value `hot`, the user should be redirected to the same template, but now a `hot = True` argument is passed, and the list of posts is ordered such that the post with the highest number of votes is at the top. In general, every time the user goes to the homepage by clicking "UnderDogs" or if the user has just logged into the website, the posts should be ordered by time (which means that these specific `render_template` functions should pass `new = True` as an argument.
The difference between the `writePosts.html` template and this one is that the form that is displayed to the user at the time of writing a post is always the same (community, post title, post text, etc.), while on the `posts.html` page the user has the ability to display the page based on one out of two criteria: either `new` or `hot` posts.
Please let me know if my answer has been helpful or if I do not understand your question.
Thank you very much, @derickfan !

**Comment by derickfan** [comment]
Ahhh I see. I changed it so that a takes a variable called sort which the template will check if it's either new or hot so that in the future if we wanted to have more sorting options we wouldn't have many if statements to check which sorting rendering statement with the right sorting variable. Also the site should now have sorting back
![Screen Shot 2019-08-17 at 9 40 45 PM](https://user-images.githubusercontent.com/22162773/63219075-0d7aed00-c138-11e9-8004-4cf61642df6b.png)
![Screen Shot 2019-08-17 at 9 43 18 PM](https://user-images.githubusercontent.com/22162773/63219071-0b189300-c138-11e9-8803-920be14119da.png)

**Comment by mary060196** [comment]
@derickfan , got it. Thank you so much for adding this nice option!

**Comment by mary060196** [comment]
It works very well! It is, hence, time to close this well-fixed issue.
