### ISSUE TITLE
After submitting post, view post not work

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#66]

**Comment by derickfan** [comment]
You can now view the post but its adding things to the end of the url
![Screen Shot 2019-08-14 at 7 25 53 PM](https://user-images.githubusercontent.com/22162773/63063202-ae17a580-bec9-11e9-8238-361ebfc6937f.png)

**Comment by Maker-Mark** [comment]
@derickfan Hmmm, weird, it took me to A post but the wrong one... You can remove the training info from the html, I think it's the "title" or value?

**Comment by Maker-Mark** [comment]
@derickfan Why if we just direct them back to the port....not the post. They can just see it there

**Comment by Maker-Mark** [comment]
@derickfan It actually seemed to work as long as the post title is unique. Are you getting the first result by title or by ID?

**Comment by derickfan** [comment]
That's weird I'm getting it by ID

**Comment by Maker-Mark** [comment]
Hmm, let me try to reproduce it again

**Comment by Maker-Mark** [comment]
@derickfan Make a new post with the same exact text as an already existing post in that port and it will take you to that one instead

**Comment by derickfan** [comment]
Hmmm thats weird

**Comment by derickfan** [comment]
Oh is it cause when we make a new post we find it by postText and since the text is the same it'll return the first instance of that
![Screen Shot 2019-08-14 at 9 42 24 PM](https://user-images.githubusercontent.com/22162773/63067327-723a0b80-bedc-11e9-98ff-f916758d2b0c.png)

**Comment by Maker-Mark** [comment]
> Oh is it cause when we make a new post we find it by postText and since the text is the same it'll return the first instance of that. Wait why are we finding it by text and not userId?
> ![Screen Shot 2019-08-14 at 9 42 24 PM](https://user-images.githubusercontent.com/22162773/63067327-723a0b80-bedc-11e9-98ff-f916758d2b0c.png)

That was a work around when the DB didnt have a method for ID yet. Can you change it to ID?

**Comment by derickfan** [comment]
Got it
