### ISSUE TITLE
"Save Post" Button is Not Operative

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#68]
Here's the image of the problem:
![image](https://user-images.githubusercontent.com/52957236/63066425-035ab380-bed8-11e9-904b-e2a5dade4925.png)

**Comment by derickfan** [comment]
We actually haven't implemented that yet. I'll start later tonight.

**Comment by mary060196** [comment]
Sure, @derickfan . No problem! Don't close this issue yet so that it won't be forgotten

**Comment by derickfan** [comment]
You should now be able to save posts and view them in your dashboard

**Comment by mary060196** [comment]
Works wonderfully! Thank you so much, @derickfan ! I close the issue now.
