### ISSUE TITLE
Sort Drop down display broken 

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#69]
![image](https://user-images.githubusercontent.com/40143016/63069242-31de8b80-bee4-11e9-948b-8289a28410e9.png)

**Comment by mary060196** [comment]
@Maker-Mark , it's broken because I changed the Jinja code as @derickfan said!

**Comment by mary060196** [comment]
See my comment to #63 .

**Comment by Maker-Mark** [comment]
> @Maker-Mark , it's broken because I changed the Jinja code as @derickfan said!

Ahh okay, I'll link up with @derickfan
