### ISSUE TITLE
Voting on Posts and Comments: Total # of Votes Incorrectly Computed

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#75]
When a user presses the "++" button once, the number of votes must increase in 1 vote. When the user presses on the "++" again, the number of votes must decrease by 1, as though as the user takes the vote back. Similarly, when the "--" is pressed once, the number of votes should decrease by 1, and when the "--" is pressed again, the number of votes should increase.

The JS function for the `posts.html` and `postDetails.html` does this on the client-side, but apparently, the python algorithm does not check on which button the user has pressed. Note that the `upOrDownvoted` argument is 1 (upvoted) or 0 (had not voted) or -1 (downvoted). This could help in constructing the algorithm to check if the user had already voted and what the total number of votes is after each button pressing.

Thank you very much for your help, Guys!

**Comment by derickfan** [comment]
Voting should now be fixed. Apparently when someone would vote on a comment it would also modify everyone's votes in that certain comment rather than just the user voting
