### ISSUE TITLE
# of Members Missing on the Trending Ports Section

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#76]
Here's the image:
![image](https://user-images.githubusercontent.com/52957236/63071583-ddd8a480-beed-11e9-8f16-73ee1d51642c.png)

**Comment by derickfan** [comment]
Now should be showing the number of members for each port. Gonna need to relog for it to show. Also when subscribing or unsubscribing the number won't update until you refresh

**Comment by mary060196** [comment]
Everything works perfectly! Wonderful job, @derickfan ! The issue is closing.
