### ISSUE TITLE
Scaling Issues for Mobile

### ISSUE THREAD

**Issue by LoadingUser3** [DataMascara/cisc3140-su19-project#78]
Hello,

This may be low on the priority list, but some parts of the site on mobile look...odd. 

My phone is 6 inches length x 3 inches width.

Here are some screenshots of how most pages of the site looks on a mobile:

### **Homepage:**

![Homepage](https://user-images.githubusercontent.com/47548948/63182996-f21dbe00-c021-11e9-8a8d-caa82bf6df3b.jpg)

----------------------------------------------------------------------------
### **Posts:**

![Post1](https://user-images.githubusercontent.com/47548948/63183003-f8139f00-c021-11e9-8616-0caf5732e33e.jpg)

![Post2](https://user-images.githubusercontent.com/47548948/63183008-f944cc00-c021-11e9-8084-df79e4a7f703.jpg)

![Post3](https://user-images.githubusercontent.com/47548948/63183018-fcd85300-c021-11e9-84bb-698bfff556c9.jpg)

----------------------------------------------------------------------------
### **User Profile:**

![UserProfile1](https://user-images.githubusercontent.com/47548948/63183040-09f54200-c022-11e9-9a54-b3afb33e37c2.jpg)

![UserProfile2](https://user-images.githubusercontent.com/47548948/63183050-0cf03280-c022-11e9-9b72-4199e9e06da6.jpg)

![UserProfile3](https://user-images.githubusercontent.com/47548948/63183056-0f528c80-c022-11e9-92c5-4152de11f8cb.jpg)

----------------------------------------------------------------------------
### **Dashboard:**

![Dashboard1](https://user-images.githubusercontent.com/47548948/63183106-2beec480-c022-11e9-9b0f-05007d06a2ae.jpg)

![Dashboard2](https://user-images.githubusercontent.com/47548948/63183112-2e511e80-c022-11e9-9d6a-1a5cf61a295a.jpg)

----------------------------------------------------------------------------
### **Account Settings:**

![AccountSettings1](https://user-images.githubusercontent.com/47548948/63183063-124d7d00-c022-11e9-9f94-414def42f5e6.jpg)

![AccountSettings2](https://user-images.githubusercontent.com/47548948/63183069-15e10400-c022-11e9-8538-3ea2aefeebb2.jpg)

On a desktop browser, the site starts to look odd when the scale hits around 900 px width.

Hope this helps!

**Comment by LoadingUser3** [comment]
Forgot to mention, I could only scroll left and right on the Posts page

**Comment by abrahym-sharfeldden** [comment]
It will help if you share the name of your device so that the media queries can target your devices pixel resolution

**Comment by LoadingUser3** [comment]
Samsung Galaxy J7 Prime

**Comment by mary060196** [comment]
Hopefully, @LoadingUser3 , media queries will be added to the website this upcoming week.

**Comment by mary060196** [comment]
Dear @LoadingUser3 ,
All media queries had been added shortly ago to the website. What it means: _any_ device from this moment and on displays a pretty and conveniently used webpage. Please refresh your browser and /or clean the cache in it (if you are using Chrome, for example, you could do this through the setting of your device. In most devices, you go to Settings -> Applications -> Installed Applications -> Chrome -> <Storage> -> Clean Cache. It is a similar procedure in most browsers. After you refresh, you should see the website as follows:
![image](https://user-images.githubusercontent.com/52957236/63583888-db1f2480-c569-11e9-9495-2df9fd23d47b.png)
Enjoy browsing, and have a great semester!
