### ISSUE TITLE
Can't Log into the Website w/ my Username and Password

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#82]
Is this a bug, or was my account deleted from the database as part of the cleaning process?

**Comment by chalshaff12** [comment]
I haven't disabled any users since Thursday, what's your username?

**Comment by mary060196** [comment]
mary060196
Thank you, Michal!

**Comment by chalshaff12** [comment]
Hmm looks like it's an active user, it should be fine from the database side..

**Comment by mary060196** [comment]
Thank you very much for your answer, @chalshaff12 !
Possibly there are issues on the Back End. In the meantime, I registered with another account with another username. I ask about this because I want to continue to debug the website, and it is difficult to do so without being logged in.
Thank you, and good luck on the final!

**Comment by abrahym-sharfeldden** [comment]
Keep in mind that if you do have trouble logging in, there is still the default login information:
username: `username`
password: `password`

**Comment by mary060196** [comment]
@abrahym-sharfeldden , thank you so much for this. Believably, there is a different problem behind this.
@derickfan : I have some more clear details about the error. When I click "Sign In", the page seems to refresh, and the URL becomes `https://bc-app-class.herokuapp.com/home/`, but what I still see as through as I am logged out. Is the `user` argument passed to this `render_template` function?
Thank you all so much!

**Comment by derickfan** [comment]
Hmmm there might be something wrong with the cookies. Can you try logging out by going to https://bc-app-class.herokuapp.com/logout and then trying to log back in?

**Comment by mary060196** [comment]
When I clicked on the link that you, @derickfan , wrote here, I was redirected to `https://bc-app-class.herokuapp.com/home/` , but I still see the page as though as I am logged out. Here's the image:
![image](https://user-images.githubusercontent.com/52957236/63219161-1cfb3580-c13a-11e9-87a9-4d91187d69f7.png)

**Comment by derickfan** [comment]
Can you try logging back in?

**Comment by mary060196** [comment]
I did so, but the condition is the same:
![image](https://user-images.githubusercontent.com/52957236/63219178-5c298680-c13a-11e9-9ba4-a295316a3cc5.png)

**Comment by derickfan** [comment]
Hmmm that's weird. I'll look into it

**Comment by mary060196** [comment]
Thank you so much, @derickfan . Meanwhile, I'll just use the other account for which I register an hour ago. If it is necessary for me to search for some file that is stored on my computer and modify it anyhow, please tell me about this.
Good luck on the final!

**Comment by derickfan** [comment]
Thanks you too

**Comment by derickfan** [comment]
Can you try logging in now?

**Comment by mary060196** [comment]
Yes!!!!! It logged me in! Thank you so, so much, @derickfan ! I so much appreciate your work!

**Comment by mary060196** [comment]
The issue shall be closed now. Thank you, everyone, for your tremendous help!
