### ISSUE TITLE
adding an 'All' feed, and/or 'my_subscriptions' feed

### ISSUE THREAD

**Issue by chalshaff12** [DataMascara/cisc3140-su19-project#86]
Right now the app opens to the 'main' port's post feed and to see posts in other ports, you have to click on them. Perhaps we should have an option for 'all' to show a feed of all posts from all ports. (Equivalent of Reddit's "All")

Another idea (not mutually exclusive) is to have something like a "my_all" or "my_subs" type of link that shows a feed with all posts in the ports I am subscribed to. (Equivalent of Reddit's "Home")

The database side of this is doable within a few hours, it may be an interesting idea to add at some point.

**Comment by derickfan** [comment]
Right now there is a "my_subs" type of link showing all the posts that you're subbed to. The only way to actually see it is manually entering in https://bc-app-class.herokuapp.com/subscribed-posts/. I can also implement an endpoint where it'll show all posts from all ports. We might also need to implement pages to our site.

**Comment by mary060196** [comment]
@derickfan , wow! I did not know about the existence of the "my_sub" link. Would it be possible, based on guidance that was given from the Product team at the beginning of the semester, to make this specific "my_sub" display type the homepage of every user once he or she logs in?

**Comment by derickfan** [comment]
That's easily doable. I'll get on that when I have time

**Comment by mary060196** [comment]
Sure, @derickfan . Thank you very much for your reply!

**Comment by mary060196** [comment]
@derickfan has successfully added the posts from all the subscribed ports to the user's homepage! Hurray! Great thanks! The issue is then closed.
