### ISSUE TITLE
Where is the member count coming from on the Trending sidebar

### ISSUE THREAD

**Issue by chalshaff12** [DataMascara/cisc3140-su19-project#87]
On the Trending ports sidebar, where is the member count of each Port coming from?

Right now it seems to be displaying member counts for all users where it should only be displaying counts for active users. I may need to update a view in the database so I'm wondering where that number is being pulled from.

**Comment by mary060196** [comment]
@chalshaff12 , you are right: based on the Back End team's implementation, it probably counts the total number of active users, but to be sure we need to ask them.
I assign @derickfan and @Maker-Mark , who can answer this question.

**Comment by derickfan** [comment]
![Screen Shot 2019-08-18 at 10 10 03 PM](https://user-images.githubusercontent.com/22162773/63234834-fd7d0f00-c204-11e9-9eea-e258245ffcda.png)
We're calling the all_subscriptions_by function for each of the ports and then using the len() function to get the size of the list which is the number of users subscribed to it

**Comment by chalshaff12** [comment]
I changed the database view to give the subscriptions only for active users, but the page still displays the old numbers. Any idea where it's going wrong?

**Comment by derickfan** [comment]
If you're logged in you're gonna need to relog to refresh the session so the trending ports will be updated

**Comment by chalshaff12** [comment]
Ah ok, looks good. Thank you!
