### ISSUE TITLE
Can no longer create a new account

### ISSUE THREAD

**Issue by derickfan** [DataMascara/cisc3140-su19-project#90]
![Screen Shot 2019-08-20 at 3 35 02 PM](https://user-images.githubusercontent.com/22162773/63378396-22d26000-c360-11e9-83ed-27f736393d10.png)
The form is asking me to match the requested format for first name

**Comment by mary060196** [comment]
I have added a `pattern` attribute to the html page that may cause this. I will remove it right now and notify you, @derickfan .

**Comment by mary060196** [comment]
I removed the `pattern`s now and committed, but it takes a few minutes to re-deploy. In 5 minutes from now, would you be able to refresh the page and try again? Thank you, @derickfan !

**Comment by mary060196** [comment]
@derickfan , try now. Does it still display this message?

**Comment by derickfan** [comment]
Yup working great thanks!
