### ISSUE TITLE
App of the Month Form Template Added, but not Recognized through Re-Deployment

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#92]
First of all, thank you very much for addressing this issue. Here are the details:
1) I added an HTML file into the templates folder called `appOfTheMonthRegister.html`.
2) Corresponding JS file was added as well.
3) The Brooklyn College Ad in `base.html` was replaced by a `gif` file, and the `href` attribute was changed to `/app-of-the-month-register/`.
4) The `app.py` file was added the following lines:
```
"""
**** App of the Month Registration Form: ****
"""

@app.route('/app-of-the-month-register/')
def appOfTheMonth():
    user = session["user"]
    trending = trending_ports()
    return render_template('appOfTheMonthRegister.html', name = "App Registration", trendPorts = trending, user = user)
```
I refreshed the page and cleaned the cache in the browser many times. The last change that I made is reflected by the redeployment (I added a slash in the `base.html` file, which I see when I refresh), but when I click on the new `gif`, I see a 500 Internal Server Error once the page redirects to `https://bc-app-class.herokuapp.com/app-of-the-month-register/`.
What should be done to have the template recognized? The template itself is not fully ready for use (a few more JavaScript functions should be added), but I first must see the template at work to finish adding this feature.

Thank you very much for your help; it is very appreciated!!!
Have a great semester!!!

**Comment by mary060196** [comment]
Great! It works now!
@derickfan , thank you very much for your assistance!!!

**Comment by derickfan** [comment]
fixed there was a "end if" statement in the template without an "if" statement

**Comment by mary060196** [comment]
Ohh, I see it! My bad! Thank you for finding this!!!
